export const MESSAGE_INFO = "MESSAGE_INFO";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_WARN = "MESSAGE_WARNING";
export const MESSAGE_ERROR = "MESSAGE_ERROR";
export const MESSAGE_LOAD = "MESSAGE_LOADING";
